"""
Django settings for pineraider project.

Generated by 'django-admin startproject' using Django 2.2.7.
"""

import os

from pineraider import settings_local

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = settings_local.SECRET_KEY

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = settings_local.DEBUG

ALLOWED_HOSTS = settings_local.ALLOWED_HOSTS


# Application definition

INSTALLED_APPS = settings_local.INSTALLED_APPS

MIDDLEWARE = settings_local.MIDDLEWARE

ROOT_URLCONF = settings_local.ROOT_URLCONF

TEMPLATES = settings_local.TEMPLATES

WSGI_APPLICATION = settings_local.WSGI_APPLICATION


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = settings_local.DATABASES


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = settings_local.AUTH_PASSWORD_VALIDATORS


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = settings_local.LANGUAGE_CODE

TIME_ZONE = settings_local.TIME_ZONE

USE_I18N = settings_local.USE_I18N

USE_L10N = settings_local.USE_L10N

USE_TZ = settings_local.USE_TZ


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = settings_local.STATIC_URL
STATIC_ROOT = settings_local.STATIC_ROOT

MEDIA_URL = settings_local.MEDIA_URL
MEDIA_ROOT = settings_local.MEDIA_ROOT