# Generated by Django 2.2.7 on 2020-01-05 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=256)),
                ('author_name', models.CharField(max_length=256)),
                ('display_on_not_found', models.BooleanField(default=False, help_text='Whether or not to display this quote on 404 pages.')),
            ],
        ),
    ]
