# Generated by Django 2.2.7 on 2020-02-11 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_schema__add_quote_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='display_publically',
            field=models.BooleanField(default=True, help_text='If toggled, this article will be accessible to the public.'),
        ),
    ]
